[package]
name = "whenever"
version = "0.0.4"
edition = "2021"

[lib]
name = "whenever"
crate-type = ["cdylib"]

[dependencies]
bincode = "1.3.3"
chrono = { version = "0.4.31", features = ["clock"] }
pyo3 = "0.20.0"
